### ISSUE TITLE
Devices do not show

### ISSUE THREAD

**Issue by natrius** [Semper-Viventem/MetaRadar#57] opened 2023-08-29 11:46 UTC
**Describe the bug**
Well, no devices are shown but in the draw-down menu of android it shows that there are 7 devices found. I can click on them even if i don't see them. 

**Expected behavior**
A list of devices.

**Screenshots**

![signal-2023-08-29-134252_002](https://github.com/Semper-Viventem/MetaRadar/assets/7243447/f5d02ff5-a2b6-4fff-b63c-e7a81f8acb3b)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 9
 - OS: Android 10
 - Browser: App
 - Version: 0.18.1-beta

I basically just need to scan my own earbuds to get them implemented somewhere else.

**Comment by Semper-Viventem** [comment] 2023-08-29 12:01
Hey, could you please
* If there are any error messages in the Journal tab
* If location is enabled for your device and granted for the app (location is needed for Bluetooth according to the Android Privacy Policies)

**Comment by Manamama** [comment] 2023-09-29 19:33
The App is amazing as I needed just this: I thought of coding it myself, but then found it in Github here, ready. Kudos. 

A tip re the above. Not sure if a bug or a feature, but with Location Always On disabled: 
![Screenshot_2023-09-29-21-25-58-71](https://github.com/Semper-Viventem/MetaRadar/assets/78492008/d4641ba0-0074-438b-8d28-048ba6818eed) it does not scan: 
![Screenshot_2023-09-29-21-28-33-26](https://github.com/Semper-Viventem/MetaRadar/assets/78492008/923e5c49-dd43-4ecf-8775-17bd81109067)
only if fully and always enabled, it does: 
![Screenshot_2023-09-29-21-29-14-04](https://github.com/Semper-Viventem/MetaRadar/assets/78492008/569aeb9e-9a32-4787-b152-9112926212e1)
(NRF Connect, EFR Connect etc do not need it always on.)

**Comment by Semper-Viventem** [comment] 2024-02-23 17:19
Hey, the app had quite a lot of updates since the report. I'll close the issue as the problem is not reproducible for me.

Responding to the question from @Manamama, the background location is required for radar working in the background because of the android security policies. We cannot obtain Bluetooth without the location permission.

**Closed by Semper-Viventem** 2024-02-23 17:19 UTC
Labels: bug

**Comment by Manamama** [comment] 2024-02-26 10:38
Quick FYI that before and after the most recent update, 0.23.0 beta, it has been working fine - two standard stock,  rooted, Oppo Droids.

**Comment by natrius** [comment] 2024-02-26 10:42
I would like to add a possible culprit for such visibility-issues: Xiaomi has some kind of automatic dark-mode even for apps that don't support it. That made some problems with another app already. 

BLE Radar works good right now, everything visible.
